version: '3'
services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: dostavim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"

  dostavim:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: dostavim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: always
    container_name: dostavim-container
    ports:
      - "80:8080"
    depends_on:
      - db
volumes:
  postgres-data: