databaseChangeLog:
  - changeSet:
      id: 4
      author: merantory
      changes:
        - tagDatabase:
            tag: productTableTag
        - sqlFile:
            dbms: "postgresql"
            relativeToChangelogFile: true
            path: sql/create_product_table.sql

      rollback:
        - sqlFile:
            dbms: "postgresql"
            relativeToChangelogFile: true
            path: sql/rollback_product_table.sql