databaseChangeLog:
  - changeSet:
      id: 6
      author: merantory
      changes:
        - tagDatabase:
            tag: product_restaurantTableTag
        - sqlFile:
            dbms: "postgresql"
            relativeToChangelogFile: true
            path: sql/create_product_restaurant_table.sql

      rollback:
        - sqlFile:
            dbms: "postgresql"
            relativeToChangelogFile: true
            path: sql/rollback_product_restaurant_table.sql