CREATE TABLE IF NOT EXISTS product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR NOT NULL,
    price       FLOAT     NOT NULL CHECK (price >= 0),
    weight      FLOAT  NOT NULL CHECK (weight > 0),
    description TEXT    NOT NULL,
    category    VARCHAR REFERENCES category(name)
);