CREATE TABLE IF NOT EXISTS comment
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id),
    person_id BIGINT NOT NULL REFERENCES person(id),
    content TEXT NOT NULL,
    UNIQUE (product_id, person_id)
);