CREATE TABLE IF NOT EXISTS person
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE ,
    password VARCHAR NOT NULL,
    first_name VARCHAR,
    second_name VARCHAR,
    address VARCHAR,
    age INT CHECK (age >= 14 AND age <= 120)
);