CREATE TABLE IF NOT EXISTS "order"
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight FLOAT NOT NULL CHECK (weight > 0),
    cost FLOAT NOT NULL CHECK (cost >= 0),
    order_date TIMESTAMPTZ NOT NULL,
    order_status VARCHAR NOT NULL,
    restaurant_id BIGINT NOT NULL REFERENCES restaurant(id),
    person_id BIGINT NOT NULL REFERENCES person(id)
);